<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>CNCDatalog</AssemblyName>
    <ApplicationIcon>static\cncmenu.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="filemonitortrayapp.cs" />
    <Compile Include="FileSelectorForm.cs" />
    <Compile Include="LocalizationManager.cs" />
    <Compile Include="LoginForm.cs" />
    <Compile Include="UserManagementForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="7.0.0" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="static\cncmenu.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>