[Tabelle]
AnzahlSpalten = 5
AnzahlZeilen = 256
HaederZeile = 1
HaederSpalte = 0
Quelle = intern
Schrifthoehe = 12
Zeilenhoehe = -1
TimeOut = 600

[Spalte1]
Breite = 40
Editierbar = 0
Ausrichtung = R

[Spalte2]
Breite = 110
Editierbar = 1
Maske = e;c;16
Ausrichtung = L

[Spalte3]
Breite = 160
Editierbar = 1
Maske = e;c;16
Ausrichtung = R
ListeDatei = Barcodeliste.ini.dat
ListeSucheInSpalte = 3

[Spalte4]
Breite = 55
Editierbar = 1
Maske = 999
Ausrichtung = R

[Spalte5]
Breite = 70
Editierbar = 1
Maske = 9999
Ausrichtung = R

[Commands]

[Buttons]
Anzahl = 0

[SystemButtons]
Sprungweite1 = 12
Sprungweite2 = 24 
GeheZu = 1
InAktiv1 = 0
Level1 = 0
Hint1 =Seite rόckwδrts;page back;Une page en arriθre;Σελιδα πισω;pagina precedente;vorige pagina;edell. sivulle;strana dozadu;Pαgina atras;Pαgina para tras;
InAktiv2 = 0
Level2 = 0
Hint2 =halbe Seite rόckwδrts;half page back;Demi-page en arriθre;Μιση σελιδα πισω;pagina seguente;halve pagina terug;½ siv. taaksepδin;polovica strany dozadu;Media pαgina atras;Voltar meia pαgina;
InAktiv3 = 0
Level3 = 0
Hint3 =halbe Seite vorwδrts;half page forward;Demi-page en avant;Μιση σελιδα μπροστα;1/2 pagina indietro;halve pagina vooruit;½ siv. eteenpδin;polovica strany dopredu;Media pαgina adelante;Adiantar meia pαgina;
InAktiv4 = 0
Level4 = 0
Hint4 =Seite vorwδrts;page forward;Une page en avant;Σελιδα μπροστα;1/2 pagina avanti;volgende pagina;seur. sivulle;strana dopredu;Pαgina adelante;Pαgina adiante;
InAktiv5 = 0
Level5 = 0
Hint5 =Export in Datei;export to file;Exporter dans fichier;Εξαγωγη σε φακελο;esporta nel file;export in bestand;export tiedostoon;export do suboru;Exportar a fichero;Exportar a fichero;
InAktiv6 = 0
Level6 = 0
Hint6 =Import aus Datei;import from file;Importer ΰ partir de fichier;Εισαγωγη απο φακελο;importa nel file;import uit bestand;import tiedostosta;import zo suboru;Importar de fichero;Importar de fichero;
InAktiv7 = 0
Level7 = 0
Hint7 =Export in Zwischenablage;copy;Exporter du presse-papier;Αντιγραφη;copia;export in copiebestand;kopioi;export do medzipamate;Copiar;Copiar;
InAktiv8 = 0
Level8 = 0
Hint8 =Import aus Zwischenablage;paste;Importer dans le presse-papiers;Επικολληση;incolla;import uit copiebestand;liitδ;import z medzipamate;Pegar;Colar;
InAktiv9 = 0
Level9 = 0
Hint9 =Zeile nach oben;move up;Monter d'une ligne;Μετακινηση πανω;sposta in alto;lijn naar boven;rivi ylφs;riadok hore;Mover arriba;Mover Para Cima;
InAktiv10 = 0
Level10 = 0
Hint10 =Zeile nach unten;move down;Descendre d'une ;Μετακινηση κατω;sposta in basso;lijn naar onder;rivi alas;riadok dole;Mover abajo;Mover Para Baixo; 
InAktiv11 = 0
Level11 = 0
Hint11 =Zeile einfόgen;insert line;Ajouter une ligne;Διαγραφη γραμμης;inserire linea;lijn invoegen;lisδδ rivi;riadok vlozit;Insertar lνnea;Inserir Linha;
InAktiv12 = 0
Level12 = 0
Hint12 =Eingabe abbrechen;cancel;Interrompre input;Εισαγωγη γραμμης;cancella;input onderbreken;peruuta;zadanie prerusit;Cancelar;Cancelar;
InAktiv13 = 0
Level13 = 0
Hint13 =Δnderung senden;save;Confirmation d'une saisie;Ακυρο;salva;verandering opslaan;tallenna;zmenu poslat;Guardar;Guardar;
InAktiv14 = 0
Level14 = 0
Hint14 =Zeile lφschen;delete line;Effacer une ;Αποθηκευση;cancellare linea;lijn verwijderen;poista rivi;riadok vymazat;Eliminar lνnea;Eliminar Linha;

[Texte]
Ueberschrift=Barcodeliste;barcodelist;Liste des codes barres;barcodelist;barcodelist;barcodelijst;viivakoodit;barcodelist;Cσdigos de barras;Cσdigos de barras;
Spalte1 =ZNr;line;N°L;line;line;lijn;Rno.;line;NΊ;N°;
Spalte2 =Lieferant;deliverer;Fournisseur;deliverer;deliverer;lieferant;alihankkija;deliverer;Enviar;Enviar;
Spalte3 =BarCode;barcode;CodeBar;barcode;barcode;barcode;viivakoodi;barcode;Codigo Barras;Codigo Barras;
Spalte4 =Stόck;piece;Qtι;Κομματια;pezzo;aantal;kappale;kus;NΊ Tableros;Peηa;
Spalte5 =Type;type;Type;Τυπος;tipo;type;tyyppi;typ;Formato;N° Chapas;

[UseBarCode]
Drucken = 1
Drucken1 = 1 
Drucken2 = 2 
Drucken3 = 5
Drucken4 = 6 
Drucken5 = -1 
UserLevel = 0
;
InsertSpalte = 3
;
ListeDatei = Barcodeliste.dat

[Spracheditor]
DateiKennung=Barcodeliste.ini;;;;;;;;;;
