[LagerUebersicht]
Ebenen = 1
Laengemm = 6000	
Breitemm = 12000
LaengePixel = 400
BreitePixel = 800
FaktorAutom = 0
Ausrichtung = 0
Schrifthoehe = 8

Dateiname = PlatzEinteilung.bin
DateinameEA = E_A_Einteilung.bin
DateinameEAConfig = E_A_Einteilung_Konfig.ini

MenuID = 16
MenuID2 = 16

RandLinksPix = 10
RandRechtsPix = 10
RandObenPix = 10
RandUntenPix = 10

//Bitmap1_x =15000
//Bitmap1_y =11000
//Bitmap1_Laenge =7000
//Bitmap1_Breite =8000
//Bitmap1_Drehung =0
//Bitmap1_Spiegeln =0
//Bitmap1_InHintergrund =1
//Bitmap1_Dateiname =C:\Program Files\LagerPC\Bitmaps\saege1.bmp

DropDownText1=Etage 1;floor 1;étage 1;Ïñïöïò 1;piano 1;floor 1;floor 1;poschodie 1;Piso 1;ANDAR 1;
DropDownText2=Etage 2;floor 2;étage 2;Ïñïöïò 2;piano2;floor 2;floor 2;poschodie 2;Piso 2;ANDAR 2;

IndexLagerPlatzEbene1= 128
IndexLagerPlatzEbene2= 256
Bitmap1_AutomAusrichten=-1

[GreiferPosition]
FastMode = 1
RealMode = 1

Greifer = 1
EbeneGreifer1=1
EbeneGreifer2=1
EbeneGreifer3=1
EbeneGreifer4=4


BitmapSchieneLaenge1 = krahnbahn_k.bmp
BitmapSchieneLaenge2 = krahnbahn_k.bmp
BitmapSchieneLaenge3 = krahnbahn_k.bmp
BitmapSchieneQuer1 = bruecke_k.bmp
BitmapSchieneQuer2 = bruecke_k.bmp
BitmapSchieneQuer3 = bruecke_k.bmp
BitmapGreifer1 = schlitten_k.bmp
BitmapGreifer2 = schlitten_k.bmp
BitmapGreifer3 = schlitten_k.bmp

'Antriebe ein
[Lampe1]
Schrifthoehe = 8
TextOFF =O;O;O;O;O;O;O;O;O;O;
TextON =I;I;I;I;I;I;I;I;I;I;
FarbeOFF = 1
FarbeON = $0080C000
Flag = 1.1
Position = 34;1
Groesse = 15;39
Hint=Sind die Antriebe gestartet?;is the motorcontrol startet?;is the motorcontrol startet?;is the motorcontrol startet?;is the motorcontrol startet?;is the motorcontrol startet?;is the motorcontrol startet?;is the motorcontrol startet?;El control del motor esta en marcha?;Motores Comutados

'Manipulator 1 referiert
[Lampe2]
Schrifthoehe = 8
TextOFF =R;R;R;R;R;R;R;R;R;R;
TextON =R;R;R;R;R;R;R;R;R;R;
FarbeOFF = 1
FarbeON = $0080C000
Flag = 1.2
Position = 48;1
Groesse = 15;13
Hint=Ist der Manipulator 1 referiert?;has the manipulator 1 already finished the reference drive?;has the manipulator 1 already finished the reference drive?;has the manipulator 1 already finished the reference drive?;has the manipulator 1 already finished the reference drive?;has the manipulator 1 already finished the reference drive?;has the manipulator 1 already finished the reference drive?;has the manipulator 1 already finished the reference drive?;El manipulador 1 termino en el punto inicial?;eixos referenciados

'Manipulator 1 gestartet
[Lampe3]
Schrifthoehe = 8
TextOFF =0;0;0;0;0;0;0;0;0;0;
TextON =1;1;1;1;1;1;1;1;1;1;
FarbeOFF = 7
FarbeON = $0080C000
Flag = 1.3
Position = 48;14
Groesse = 15;13
Hint=Ist der Manipulator 1 im Automatikmodus?;is manipulator 1 in automatic mode?;is manipulator 1 in automatic mode?;is manipulator 1 in automatic mode?;is manipulator 1 in automatic mode?;is manipulator 1 in automatic mode?;is manipulator 1 in automatic mode?;is manipulator 1 in automatic mode?;El manipulador 1 esta en modo automático?;Automatico ativo

'Manipulator 1 aktiv
[Lampe4]
Schrifthoehe = 8
TextOFF =0;0;0;0;0;0;0;0;0;0;
TextON =1;1;1;1;1;1;1;1;1;1;
FarbeOFF = 7
FarbeON = 6
Flag = 1.4
Position = 48;27
Groesse = 15;13
Hint=Ist der Manipulator 1 momentan aktiv?;is manipulator 1 working at this moment?;is manipulator 1 working at this moment?;is manipulator 1 working at this moment?;is manipulator 1 working at this moment?;is manipulator 1 working at this moment?;is manipulator 1 working at this moment?;is manipulator 1 working at this moment?;El manipulador 1 esta trabajando en este momento?;O manipulador 1 esta ativo

'Greifer 1
[Lampe30]
Schrifthoehe = 12
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeON = 1
FarbeOFF = $00505080
Flag = 3.3
BlinkFlag = 3.4
Position = 328;50
Groesse = 20;20
Hint=Greifer 1 in Automatik;;;;;;;;;;;

[Lampe31]
Schrifthoehe = 12
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = $00508050
FarbeON = $0050F000
Flag = 3.1
BlinkFlag = 3.2
Position = 328;25
Groesse = 20;20
Hint=Greifer in Automatik;;;;;;;;;;;

[Text30]
Schrifthoehe = 12
Text =Greifer 1;Manipulator 1;;;;;;;;;;
Farbe = 0
Position = 305;2
FarbeHintergrund= $00F5F5F5

; 'Schubladenbuffer
; [Lampe32]
; Schrifthoehe = 12	
; TextOFF =;;;;;;;;;; 
; TextON =;;;;;;;;;;
; FarbeON = 1
; FarbeOFF = $00505080
; Flag = 3.11
; BlinkFlag = 3.12
; Position = 600;50
; Groesse = 20;20
; Hint=Schubladenbuffer in Automatik;;;;;;;;;;;

; [Lampe33]
; Schrifthoehe = 12
; TextOFF =;;;;;;;;;; 
; TextON =;;;;;;;;;;
; FarbeOFF = $00508050
; FarbeON = $0050F000
; Flag = 3.9
; BlinkFlag = 3.10
; Position = 600;25
; Groesse = 20;20
; Hint=Schubladenbuffer in Automatik;;;;;;;;;;;

; [Text31]
; Schrifthoehe = 12
; Text =Schubladenbuffer;Drawer buffer;;;;;;;;;;
; Farbe = 0
; Position = 555;2
; FarbeHintergrund= $00F5F5F5

'Automtatik TR KAM Auslauf
[Lampe40]
Schrifthoehe = 12
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeON = 1
FarbeOFF = $00505080
Flag = 3.7
BlinkFlag = 3.8
Position = 450;50
Groesse = 20;20
Hint=TR KAM Auslauf in Automatik;;;;;;;;;;;

[Lampe41]
Schrifthoehe = 12
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = $00508050
FarbeON = $0050F000
Flag = 3.5
BlinkFlag = 3.6
Position = 450;25
Groesse = 20;20
Hint=TR KAM Auslauf in Automatik;;;;;;;;;;;

[Text7]
Schrifthoehe = 12
Text =TR Auslauf KAM;;;;;;;;;;;
Farbe = 0
Position = 405;2
FarbeHintergrund= $00F5F5F5

'Zugangskontrolle LS 1
[Lampe42]
Schrifthoehe = 8
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = 1
FarbeON = $0080C000
Flag = 2.10
Position = 780;1
Groesse = 15;13
Hint=Zutritt bei Lichtschranke 1;access at gate 1;access at BI 1;access at gate 1;access at gate 1;access at gate 1;access at gate 1;access at gate 1;Acceso a la puerta 1;Acesso a barreira de luz 1

[Text1]
Schrifthoehe = 8
Text =LS 1;gate 1;BI 1;gate 1;gate 1;gate 1;gate 1;gate 1;Puerta 1;Barreira luz 1
Farbe = 0
Position = 800;0
FarbeHintergrund= $00F5F5F5

'Zugangskontrolle LS 2
[Lampe43]
Schrifthoehe = 8
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = 1
FarbeON = $0080C000
Flag = 2.11
Position = 780;14
Groesse = 15;13
Hint=Zutritt bei Lichtschranke 2;access at gate 2;access at BI 2;access at gate 2;access at gate 2;access at gate 2;access at gate 2;access at gate 2;Acceso a la puerta 2;Acesso a barreira de luz 2

[Text2]
Schrifthoehe = 8
Text =LS 2;gate 2;BI 2;gate 2;gate 2;gate 2;gate 2;gate 2;Puerta 2;Barreira luz 2
Farbe = 0
Position = 800;13
FarbeHintergrund= $00F5F5F5

'Zugangskontrolle Tuer 1
[Lampe45]
Schrifthoehe = 8
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = 1
FarbeON = $0080C000
Flag = 2.13
Position = 850;1
Groesse = 15;13
Hint=Türe 1 geöffnet;door is open;Porte ouvert;door is open;door is open;door is open;door is open;door is open;La puerta esta abierta;Porta esta aberto

[Text9]
Schrifthoehe = 8
Text =TÜR;door;PORTE;door;door;door;door;door;Puerta;porta
Farbe = 0
Position = 870;1
FarbeHintergrund= $00F5F5F5

'Schleppkontrolle
[Lampe46]
Schrifthoehe = 8
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = 1
FarbeON = $0080C000
Flag = 2.23
Position = 850;14
Groesse = 15;13
Hint=Positionskontrolle OK;Position OK;Position OK;Position OK;Position OK;Position OK;Position OK;Position OK;Position OK;Position OK

[Text10]
Schrifthoehe = 8
Text =Positionskontrolle;Positioncontrol;Positioncontrol;Positioncontrol;Positioncontrol;Positioncontrol;Positioncontrol;Positioncontrol;Positioncontrol
Farbe = 0
Position = 870;14
FarbeHintergrund= $00F5F5F5

'Teil TR A bereit
[Lampe48]
Schrifthoehe = 8
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = 1
FarbeON = $0080C000
Flag = 2.16
Position = 546;620
Groesse = 15;13
Hint=;;;;;;;;;;

[Text12]
Schrifthoehe = 8
Text =Teil auf Rifo B2 bereit;;;;;;;;;;
Farbe = 0
Position = 566;620
FarbeHintergrund= $00F5F5F5


'Vorschub läuft
[Lampe52]
Schrifthoehe = 8
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = 1
FarbeON = $0080C000
Flag = 2.20
Position = 546;633
Groesse = 15;13
Hint= Gruen = Vorschub laeuft;;;;;;;;;;

[Text16]
Schrifthoehe = 8
Text =Vorschub läuft;;;;;;;;;;
Farbe = 0
Position = 566;633
FarbeHintergrund= $00F5F5F5

'Einlaufsperre zu KAM
[Lampe53]
Schrifthoehe = 8
TextOFF =OK;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = $0080C000
FarbeON = 
Flag = 2.21
Position = 546;646
Groesse = 15;13
Hint= Schwarz = Einlaufsperre;;;;;;;;;;

[Text17]
Schrifthoehe = 8
Text =Einlaufsperre zu KAM;;;;;;;;;;
Farbe = 0
Position = 566;646
FarbeHintergrund= $00F5F5F5

'Fehler bekanntungsreihenfolge
[Lampe54]
Schrifthoehe = 8
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = $0080C000
FarbeON = 1
Flag = 2.22
Position = 746;633
Groesse = 25;25
Hint= Rot = Fehler;;;;;;;;;;

[Text18]
Schrifthoehe = 8
Text =Fehler Bekanntungsreihenfolge;;;;;;;;;;
Farbe = 0
Position = 775;633
FarbeHintergrund= $00F5F5F5

'Datenfehler vorhanden
[Lampe57]
Schrifthoehe = 8
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeOFF = $0080C000
FarbeON = 1
Flag = 2.25
Position = 920;1
Groesse = 15;13
Hint=Datenfehler vorhanden;

[Text21]
Schrifthoehe = 8
Text =Datenfehler;
Farbe = 0
Position = 940;1
FarbeHintergrund= $00F5F5F5

'Datenfehler vorhanden
[Lampe58]
Schrifthoehe = 8
TextOFF =;;;;;;;;;; 
TextON =;;;;;;;;;;
FarbeON = $0080C000
FarbeOFF = 1
Flag = 2.19
Position = 1020;1
Groesse = 15;13
Hint=Schluesselschalter;

[Text22]
Schrifthoehe = 8
Text =Schluesselschalter;
Farbe = 0
Position = 1040;1
FarbeHintergrund= $00F5F5F5

[Taster_Platz1_aktiv_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz1_Taste
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 500;510
Groesse = 200;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz1_aktiv_1

[Taster_Platz1_reset_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz1_reset
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 700;510
Groesse = 60;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz1_voll_1

[Text_Platz1]
Schrifthoehe = 42
Text =1;;;;;;;;;;
Farbe = 0
Position = 800;510
FarbeHintergrund=

[Taster_Platz2_aktiv_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz2_Taste
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 500;440
Groesse = 200;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz2_aktiv_1

[Taster_Platz2_reset_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz2_reset
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 700;440
Groesse = 60;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz2_voll_1

[Text_Platz2]
Schrifthoehe = 42
Text =2;;;;;;;;;;
Farbe = 0
Position = 800;440
FarbeHintergrund=

[Taster_Platz3_aktiv_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz3_Taste
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 500;370
Groesse = 200;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz3_aktiv_1

[Taster_Platz3_reset_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz3_reset
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 700;370
Groesse = 60;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz3_voll_1

[Text_Platz3]
Schrifthoehe = 42
Text =3;;;;;;;;;;
Farbe = 0
Position = 800;370
FarbeHintergrund=

[Taster_Platz4_aktiv_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz4_Taste
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 500;300
Groesse = 200;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz4_aktiv_1

[Taster_Platz4_reset_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz4_reset
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 700;300
Groesse = 60;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz4_voll_1

[Text_Platz4]
Schrifthoehe = 42
Text =4;;;;;;;;;;
Farbe = 0
Position = 800;300
FarbeHintergrund=

[Taster_Platz5_aktiv_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz5_Taste
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 500;230
Groesse = 200;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz5_aktiv_1

[Taster_Platz5_reset_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz5_reset
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 700;230
Groesse = 60;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz5_voll_1

[Text_Platz5]
Schrifthoehe = 42
Text =5;;;;;;;;;;
Farbe = 0
Position = 800;230
FarbeHintergrund=

[Taster_Platz6_aktiv_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz6_Taste
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 500;160
Groesse = 200;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz6_aktiv_1

[Taster_Platz6_reset_1]
Schrifthoehe = 12
Flag = 
PLCVariable = Abstapelplatz_Auswahl1.sPlatz6_reset
PLCOffset = 0
PLCSize = 4
PLCBit = 1
AlwaysEnabled = 1
Lockable = 0
Position = 700;160
Groesse = 60;60
Hint=;;;;;;;;;;
Lampe = Lampe_Platz6_voll_1

[Text_Platz6]
Schrifthoehe = 42
Text =6;;;;;;;;;;
Farbe = 0
Position = 800;160
FarbeHintergrund=

[Greifer1]
PLCvariable = Achsparameter
Greiferoffset = 0
Xoffset = 8
Yoffset = 108
Zoffset = 208
Roffset = 308
Loffset = 408

FeldAktiv = 1
FeldLinks = 65
FeldOben = 1   
FeldBreite = 200
FeldHöhe = 40
FeldFarbe = $00e0c0b8
Schriftgröße = 9

AnzeigeNrAktiv = 1
AnzeigeNrLinks = 3
AnzeigeNrOben = 2

AnzeigeXAktiv = 1
AnzeigeXLinks = 20
AnzeigeXOben = 2

AnzeigeYAktiv = 1
AnzeigeYLinks = 80
AnzeigeYOben = 2

AnzeigeZAktiv = 1
AnzeigeZLinks = 140
AnzeigeZOben = 2

AnzeigeRotAktiv = 1
AnzeigeRotLinks = 80
AnzeigeRotOben = 18

AnzeigeLAktiv = 1
AnzeigeLLinks = 140
AnzeigeLOben = 18

